# 개발 서버 테스트
@hostname = 127.0.0.1
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
###
# 사용자 조회
GET http://{{host}}/users/ HTTP/1.1

###
# 사용자 조회, 최대 갯수 제한
GET http://{{host}}/users?limit=2 HTTP/1.1

###
# 사용자 조회, limit 오류
GET http://{{host}}/users?limit=two HTTP/1.1

###
# 사용자 조회, ID
GET http://{{host}}/users/1 HTTP/1.1

###
# 사용자 조회, ID 오류
GET http://{{host}}/users/one HTTP/1.1

###
# 사용자 조회, ID 조회 실패
GET http://{{host}}/users/9 HTTP/1.1

### 
# 사용자 삭제
DELETE http://{{host}}/users/3 HTTP/1.1

### 
# 사용자 삭제, ID 오류
DELETE http://{{host}}/users/three HTTP/1.1

### 
# 사용자 추가
POST http://{{host}}/users/ HTTP/1.1
content-type: {{contentType}}

{ "name" : "Daniel" }

### 
# 사용자 추가
POST http://{{host}}/users/ HTTP/1.1
content-type: {{contentType}}

{ "name" : "Alice" }
